Bookstore/Controllers/CarttController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bookstore.Models;

namespace Bookstore.Controllers
{
    public class CarttController : Controller
    {
        BookstoreEntities db = new BookstoreEntities();
        // GET: Cartt
        public ActionResult cartt()
        {
            return View();
        }
        public ActionResult OrderNow1(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            if (Session["Cart"] == null)
            {
                List<Cart__> IsCart = new List<Cart__>
                {
                 new Cart__(db.RecentBooks.Find(id),1)

                };
                Session["Cart"] = IsCart;
            }
            else
            {
                List<Cart__> IsCart = (List<Cart__>)Session["Cart"];
                int check = IsExistingCheck(id);
                if (check == -1)
                    IsCart.Add(new Cart__(db.RecentBooks.Find(id), 1));

                else
                    IsCart[check].Quantity++;
                //IsCart.Add(new Cart(db.Products.Find(id), 1));
                Session["Cart"] = IsCart;

            }

            return View("cartt");
        }

        public int IsExistingCheck(int? id)

        {

            List<Cart__> IsCart = (List<Cart__>)Session["Cart"];
            for (int i = 0; i < IsCart.Count; i++)
            {
                if (IsCart[i].RecentBook.Id == id) return i;
            }


            return -1;

        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            int check = IsExistingCheck(id);
            List<Cart__> IsCart = (List<Cart__>)Session["Cart"];
            IsCart.RemoveAt(check);
            return View("cartt");
        }

    }
}

Bookstore/Controllers/Product_singleController.cs
using Bookstore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace  Bookstore.Controllers
{
    public class Product_singleController : Controller
    {
        BookstoreEntities db = new BookstoreEntities();
        // GET: Product_single
        public ActionResult product_single(int? id)
        {
            var Recommendlist = db.RecommendBooks.OrderBy(x => x.Id).ToList();
            ViewData["recent"] = Recommendlist;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecommendBook recom = db.RecommendBooks.Find(id);
            if (recom == null)
            {
                return HttpNotFound();
            }
            return View(recom);

           

        }
        public ActionResult product_single_(int? id)
        {
            var Recommendlist = db.RecommendBooks.OrderBy(x => x.Id).ToList();
            ViewData["recent"] = Recommendlist;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecentBook recom = db.RecentBooks.Find(id);
            if (recom == null)
            {
                return HttpNotFound();
            }
            return View(recom);



        }



    }
}

Bookstore/Views/Product_single/product_single.cshtml
@{  Layout = "~/Views/Layout/_main.cshtml";}
@using Bookstore.Models

    <div class="breadcrumb">
        <div class="container">
            <a class="breadcrumb-item" href='@Url.Action("index", "Home")'>Home</a>
            <span class="breadcrumb-item active">Product</span>
        </div>
    </div>
    <section class="product-sec">
    <div class="container">
      
        <div class="row">
            <div class="col-md-6 slider-sec">
                <!-- main slider carousel -->
                <div id="myCarousel" class="carousel slide">
                    <!-- main slider carousel items -->
                    <div class="carousel-inner">
                        <img src='@Url.Content("~/images/"+Model.Image)' />
                    </div>
                   
             
                    
                </div>
                <!--/main slider carousel-->
            </div>
            <div class="col-md-6 slider-content">

                <ul>
                    <li>
                        <span class="name">Product Name</span><span class="clm">:</span>
                        <span class="price">@Model.RecommendBookName </span>
                    </li>

                    <li>
                        <span class="name">Kindle Price</span><span class="clm">:</span>
                        <span class="price final">$@Model.Price</span>
                    </li>
                    <li><span class="save-cost">Save $7.62 (69%)</span></li>
                </ul>
                <div class="btn-sec">
                    <a class="btn" href='@Url.Action("OrderNow", "Cart", new { id = Model.Id }, null)'>Add To cart</a>
                    <button class="btn black">Buy Now</button>
                </div>
            </div>
        </div>
        </div>
</section>
    <section class="related-books">
        <div class="container">
            <h2>You may also like these book</h2>
            <div class="recomended-sec">
                <div class="row">
                    @{
                        foreach (var item in ViewData["recent"] as List<RecommendBook>)
                        {
                            <div class="col-lg-3 col-md-6">
                                <div class="item">
                                    <img src='@Url.Content("~/images/"+item.Image)' />
                                    <h3> @item.RecommendBookName</h3>
                                    <h6><span class="price">$@item.Price</span> / <a href='@Url.Action("product_single", "Product_single")'>Buy Now</a></h6>
                                    <div class="hover">
                                        <a href='@Url.Action("product_single", "Product_single",new { id=item.Id},null)'>
                                            <span><i class="fa fa-long-arrow-right" aria-hidden="true"></i></span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        }
                    }
               
                </div>
            </div>
        </div>
    </section>

Bookstore/Views/Product_single/product_single_.cshtml
@{  Layout = "~/Views/Layout/_main.cshtml";}
@using Bookstore.Models


<div class="breadcrumb">
    <div class="container">
        <a class="breadcrumb-item" href='@Url.Action("index", "Home")'>Home</a>
        <span class="breadcrumb-item active">Product</span>
    </div>
</div>
<section class="product-sec">
    <div class="container">

        <div class="row">
            <div class="col-md-6 slider-sec">
                <!-- main slider carousel -->
                <div id="myCarousel" class="carousel slide">
                    <!-- main slider carousel items -->
                    <div class="carousel-inner">
                        <img src='@Url.Content("~/images/"+Model.Image)' />
                    </div>



                </div>
                <!--/main slider carousel-->
            </div>
            <div class="col-md-6 slider-content">

                <ul>
                    <li>
                        <span class="name">Product Name</span><span class="clm">:</span>
                        <span class="price">@Model.RecentBook1 </span>
                    </li>

                    <li>
                        <span class="name">Kindle Price</span><span class="clm">:</span>
                        <span class="price final">$@Model.Price</span>
                    </li>
                    <li><span class="save-cost">Save $7.62 (69%)</span></li>
                </ul>
                <div class="btn-sec">
                    <a class="btn" href='@Url.Action("OrderNow1", "Cartt", new { id = Model.Id }, null)'>Add To cart</a>
                    <button class="btn black">Buy Now</button>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="related-books">
    <div class="container">
        <h2>You may also like these book</h2>
        <div class="recomended-sec">
            <div class="row">
                @{
                    foreach (var item in ViewData["recent"] as List<RecommendBook>)
                    {
                        <div class="col-lg-3 col-md-6">
                            <div class="item">
                                <img src='@Url.Content("~/images/"+item.Image)' />
                                <h3> @item.RecommendBookName</h3>
                                <h6><span class="price">$@item.Price</span> / <a href='@Url.Action("product_single", "Product_single")'>Buy Now</a></h6>
                                <div class="hover">
                                    <a href='@Url.Action("product_single", "Product_single",new { id=item.Id},null)'>
                                        <span><i class="fa fa-long-arrow-right" aria-hidden="true"></i></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    }
                }

            </div>
        </div>
    </div>
</section>