Bookstore/Controllers/FaqController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace  Bookstore.Controllers
{
    public class FaqController : Controller
    {
        // GET: Faq
        public ActionResult faq()
        {
            return View();
        }
    }
}

Bookstore/Controllers/Privacy_policyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bookstore.Controllers
{
    public class Privacy_policyController : Controller
    {
        // GET: Privacy_policy
        public ActionResult privacy_policy()
        {
            return View();
        }
    }
}

Bookstore/Controllers/Product_singleController.cs
using Bookstore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace  Bookstore.Controllers
{
    public class Product_singleController : Controller
    {
        BookstoreEntities db = new BookstoreEntities();
        // GET: Product_single
        public ActionResult product_single(int? id)
        {
            var Recommendlist = db.RecommendBooks.OrderBy(x => x.Id).ToList();
            ViewData["recent"] = Recommendlist;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecommendBook recom = db.RecommendBooks.Find(id);
            if (recom == null)
            {
                return HttpNotFound();
            }
            return View(recom);

           

        }
        public ActionResult product_single_(int? id)
        {
            var Recommendlist = db.RecommendBooks.OrderBy(x => x.Id).ToList();
            ViewData["recent"] = Recommendlist;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecentBook recom = db.RecentBooks.Find(id);
            if (recom == null)
            {
                return HttpNotFound();
            }
            return View(recom);



        }



    }
}

Bookstore/Views/Layout/_main.cshtml
@using Bookstore.Models
<!DOCTYPE html>
<html lang="en">
@{ 

    List<Cart> temp1 = (List<Cart>)Session["Cart"];
    if  (temp1 != null)
    {
  
        ViewData["nn"] = temp1.Count();
    }
    var count = ViewData["nn"];
}

<head>
    <meta charset="UTF-8">
    <title>Book Store</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#03a6f3">
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/styles.css">
    <link href="~/css/checkout.css" rel="stylesheet" />
</head>

<body>
    <header>
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-md-3"><a href='@Url.Action("product_single", "Product_single")' class="web-url">www.bookstore.com</a></div>
                    <div class="col-md-6">
                        <h5>Free Shipping Over $99 + 3 Free Samples With Every Order</h5>
                    </div>
                    <div class="col-md-3">
                        <span class="ph-number">Call :08033482686</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="main-menu">
            <div class="container">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <a class="navbar-brand" href='@Url.Action("index", "Home")'><img src="~/images/logo.png" alt="logo"></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="navbar-item active" >
                                @Html.ActionLink("Home", "index", "Home")
                            </li>
                            <li class="navbar-item">
                                @Html.ActionLink("Shop", "shop", "Shop")
                            </li>
                            <li class="navbar-item">
                                @Html.ActionLink("About", "about", "About")

                            </li>
                            <li class="navbar-item ">
                                @Html.ActionLink("FAQ", "faq", "Faq")
                            </li>
                            <li class="navbar-item">
                                @Html.ActionLink("Login", "login", "Login")
                            </li>
                        </ul>
                  
                        <div class="cart my-2 my-lg-0">
                            <span>
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            </span>
                            <span class="quntity">@count</span>
                        </div>
                        <form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search here..." aria-label="Search">
                            <span class="fa fa-search"></span>
                        </form>
                    </div>
                </nav>
            </div>
        </div>
    </header>
    @RenderBody()
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="address">
                        <h4>Our Address</h4>
                        <h6>
                            The BookStore Home
                            Awolowo way Ikeja Lagos,Nigeria
                        </h6>
                        <h6>Call : 08033482686</h6>
                        <h6>Email : frajohn011@gmail.com</h6>
                    </div>
                    <div class="timing">
                        <h4>Timing</h4>
                        <h6>Mon - Fri: 7am - 10pm</h6>
                        <h6>​​Saturday: 8am - 10pm</h6>
                        <h6>​Sunday: 8am - 11pm</h6>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="navigation">
                        <h4>Navigation</h4>
                        <ul>
                            <li> @Html.ActionLink("Home", "index", "Home")</li>
                            <li>@Html.ActionLink("About", "about", "About")</li>
                            <li>@Html.ActionLink("Privacy Policy", "Privacy_policy", "Privacy_policy")</li>
                            <li>@Html.ActionLink("Terms", "terms_conditions", "Terms_condition")</li>
                            <li>@Html.ActionLink("Products", "products", "Products")</li>

                        </ul>
                    </div>
                    <div class="navigation">
                        <h4>Help</h4>
                        <ul>

                            <li>@Html.ActionLink("Shipping", "shipping", "Shipping")</li>
                            <li>@Html.ActionLink("Privacy Policy", "Privacy_policy", "Privacy_policy")</li>
                            <li>@Html.ActionLink("FAQ", "faq", "Faq")</li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="form">
                        <h3>Quick Contact us</h3>
                        <h6>
                            We are now offering some good discount
                            on selected books go and shop them
                        </h6>
                        <form>
                            <div class="row">
                                <div class="col-md-6">
                                    <input placeholder="Name" required>
                                </div>
                                <div class="col-md-6">
                                    <input type="email" placeholder="Email" required>
                                </div>
                                <div class="col-md-12">
                                    <textarea placeholder="Messege"></textarea>
                                </div>
                                <div class="col-md-12">
                                    <button class="btn black">Alright, Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <h5>(C) 2019. All Rights Reserved. BookStore Frajohn</h5>
                    </div>
                    <div class="col-md-6">
                        <div class="share align-middle">
                            <span class="fb"><i class="fa fa-facebook-official"></i></span>
                            <span class="instagram"><i class="fa fa-instagram"></i></span>
                            <span class="twitter"><i class="fa fa-twitter"></i></span>
                            <span class="pinterest"><i class="fa fa-pinterest"></i></span>
                            <span class="google"><i class="fa fa-google-plus"></i></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/custom.js"></script>
</body>

</html>